# Start non-login shells to prevent macOS path_helper from reshuffling PATH
set -g default-command "zsh"

# terminal options
set -g default-terminal 'screen-256color'
set-option -g terminal-overrides ",xterm-256color:RGB"
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# increase history limit
set-option -g history-limit 100000

# allow mouse input
set -g mouse on

# use vi keys for navigating in copy mode
setw -g mode-keys vi

# monitor for activity
setw -g monitor-activity on
set -g visual-activity on

# window and status styling
set -g set-titles on
set -g allow-rename off
set -g set-titles-string "[ #S ]"
set -g window-status-format "#I:#W"
set -g window-status-current-format "#I:#W*"
set -g status-left ''
set -g status-right ''
set -g status-style fg=black,bg=color5

# base index for windows starts at 1 instead of 0
# I do this because now <prefix> 1-9 will jump straight to the window, when panes start with 0 its a longer reach with the fingers
# this starts the hotkeys at 1 instead of 0
set -g base-index 1
# do the same for panes and sessions
setw -g pane-base-index 1

# setting delay between prefix and command
set -s escape-time 1

# change prefix to M-a (can use capslock key as meta on macos in keyboard settings (set it to options key))
unbind M-a
set -g prefix M-a
bind M-a send-prefix

# keybind to source this file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# easier way to remember split hotkeys
bind | split-window -h
bind - split-window -v

# moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# toggle between last session
bind-key t switch-client -l

# clock mode
bind-key T clock-mode

# show and hide status bar
bind b set -g status

# move left and right between windows
bind -r M-h select-window -t :-
bind -r M-l select-window -t :+

# window resize
bind -r H resize-pane -L 15
bind -r J resize-pane -D 15
bind -r K resize-pane -U 15
bind -r L resize-pane -R 15

# Break pane into new named window
bind-key p command-prompt -p "New window:" "break-pane -n '%%'"
# Send Pane to existing window
bind-key P command-prompt -p "send pane to:"  "join-pane -t '%%'"
# Break into new default named window
bind-key B break-pane
# yank pane into current window
bind-key y command-prompt -p "join pane from:"  "join-pane -s '%%'"

# default hotkeys to remember

# s - Show your current list of sessions, navigate between them. THIS IS VERY USEFUL. If you remember one built in command remember this one
# q - show pane numbers and active pane within current window
# z - zoom in on current pane, prefix -> z again to toggle back
# { and } to swap current pane back and forward

# built in layout hotkeys
# pressing prefix plus meta/option and numbers 1-5 will use one of tmux's built in layouts

# cheat sheet for organizing windows with 1-4 panes

# 2 panes
# option-1 for side by side
# option-2 for one over the other

# 3 panes (hint, use swap pane hotkey as described above to move your desired pane to be pane 1)
# option-4 for one main vertical pane on the left and the other 2 panes split one over the other on the right
# option-6 for one main horizontal pane on the bottom and the other 2 panes split side by side on the top

# 4 panes
# option-5 for a tiled quad split
# option-4 and option-6 work similar as in the 3 pane example
